"""The armada Python SDK: `task` defines a task, `recipe` its environment, `sh` a command a body may return,
`connect` the deployment. `python -m armada push` sends a project's task folder; `.map`, `.stream`, `.run` and
`.local` run a task by its id."""

from .client import Armada, Connection, JobStatus, RequestError, Summary, TaskCounts, Vessel, connect, summary_of
from .recipe import RecipeBuilder, debian, from_, recipe
from .sh import Completed, OutFile, Shell, ShellError, out_file, quote, raw, sh
from .task import (
                   Cancelled,
                   Context,
                   Errored,
                   Job,
                   Lost,
                   MapError,
                   Meta,
                   Ok,
                   RemoteError,
                   Result,
                   SchemaError,
                   Task,
                   TimedOut,
                   Validator,
                   task,
)

__all__ = [
                   "Armada",
                   "Cancelled",
                   "Completed",
                   "Connection",
                   "Context",
                   "Errored",
                   "Job",
                   "JobStatus",
                   "Lost",
                   "MapError",
                   "Meta",
                   "Ok",
                   "OutFile",
                   "RecipeBuilder",
                   "RemoteError",
                   "RequestError",
                   "Result",
                   "SchemaError",
                   "Shell",
                   "ShellError",
                   "Summary",
                   "Task",
                   "TaskCounts",
                   "TimedOut",
                   "Validator",
                   "Vessel",
                   "connect",
                   "debian",
                   "from_",
                   "out_file",
                   "quote",
                   "raw",
                   "recipe",
                   "sh",
                   "summary_of",
                   "task",
]
